### PR TITLE
Hyper-V Fixes for Hydrogen

### PR DESCRIPTION
**Pull request by TriJetScud**
The following pull request resolves the following issues with VyOS under a Hyper-V Host:
- During installation of VyOS to system, the system detects there are 2 VHD's attached to the IDE bus when in fact there is only one VHD attached to the bus. By backporting fixes from later upstream kernel branches that ignores the duplicate VHD, this patch resolves the issue.
- NetVSC - Disconnecting and Reconnecting the NIC shouldn't cause any kernel warnings anymore.

IIRC, VLAN Trunking functionality is still unimplemented in the 3.8 branch. I may backport those fixes if there is a significant demand for it.

### CODE REVIEW

**Comment by alexharpin** [comment]
Just going back through some of the requests and doing a bit of a clean up.  Does this still apply to the current kernel version or have these issues been resolved in 3.13.11?  I can see these have been back ported from the 3.8 branch, so I'm presuming they have, just wanted to check before closing this request.

**Comment by dmbaturin** [comment]
Yeah, the pull request was created right when we were migrating to the 3.13 kernel. I think it's safe to close it now, but still I'd like some input from @TriJetScud before closing it.

**Comment by TriJetScud** [comment]
Most of the commits I’ve referenced has been merged with upstream already. This merge request may be closed without any further review.

**Comment by dmbaturin** [comment]
Cool, thanks!

**Pull request closed without merging**
